<a href="https://colab.research.google.com/github/aryaar2004/AI-ASSIGNMENT-2/blob/main/ai_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What this Colab code does

Installs necessary libraries.

Loads Iris dataset (built into scikit-learn).

Trains a RandomForest classifier.

Prints accuracy, confusion matrix, and classification report.

Saves the model (iris_model.joblib) in Colab.

Tests prediction for a sample [5.1, 3.5, 1.4, 0.2].

In [ ]:
# === Step 1: Install dependencies ===
!pip install scikit-learn joblib

# === Step 2: Imports ===
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib

# === Step 3: Load dataset ===
iris = load_iris()
X, y = iris.data, iris.target
target_names = iris.target_names

# === Step 4: Split data ===
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# === Step 5: Train model ===
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# === Step 6: Evaluate model ===
y_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("✅ Accuracy:", acc)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=target_names))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# === Step 7: Save model ===
joblib.dump(clf, "iris_model.joblib")
print("\nModel saved as iris_model.joblib")

# === Step 8: Try prediction ===
sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # sepal_len, sepal_wid, petal_len, petal_wid
pred = clf.predict(sample)[0]
proba = clf.predict_proba(sample)[0]

print("\nSample Input:", sample.tolist()[0])
print("Predicted Class:", target_names[pred])
print("Probabilities:", dict(zip(target_names, proba)))


✅ Accuracy: 0.9

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.82      0.90      0.86        10
   virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]

Model saved as iris_model.joblib

Sample Input: [5.1, 3.5, 1.4, 0.2]
Predicted Class: setosa
Probabilities: {np.str_('setosa'): np.float64(1.0), np.str_('versicolor'): np.float64(0.0), np.str_('virginica'): np.float64(0.0)}
